Add CloudNet Template of Issue #153
PufferPanel/templates pull request #154
Opened 2022-05-19 11:46 UTC by 2020Sanoj

Add CloudNet Template of Issue #153

2022-05-24 01:58 UTC, LordRalex requested changes

2022-05-24 01:58 UTC, LordRalex commented on cloudnet/cloudnet.json
> +        "chmod -R 777 ."
777 on an entire folder is bad
Only files which need some special perm should be handled. I would assume chmod +x start.sh

Also, the start.sh is bad for us. It runs screen, which is not what we want. The command should be ripped out, and added appropriately.

Also add java as a requirement. Refer to Minecraft templates.

2022-06-02 03:51 UTC, LordRalex requested changes

2022-06-02 03:51 UTC, LordRalex commented on cloudnet/cloudnet.json
> +    "command": "java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -Dfile.encoding=UTF-8 -Xmx${memor
Doesn't use the variable defined below

2022-06-02 03:52 UTC, LordRalex commented
Also missing requirements. Refer to Minecraft templates for examples

2022-06-02 04:26 UTC, 2020Sanoj commented
It seems that the github api has currently problems with the workflows

2022-10-28 18:03 UTC, closed without merging