Add cs2 template
PufferPanel/templates pull request #260
Opened 2024-02-13 10:59 UTC by Lok3rn3t

2024-02-13 11:01 UTC, Lok3rn3t commented
Official documentation from valve was used as the main material
https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers

2024-02-13 12:11 UTC, rcv11x commented
I will test it later on my server and confirm if there are any problems 👍🏻

2024-02-13 15:26 UTC, Lok3rn3t commented
> I will test it later on my server and confirm if there are any problems 👍🏻

snx

2024-04-03 20:31 UTC, XKinrowd commented
Hey, the template works flawlessly for me, but it seems like the game_alias cvar is case-sensitive. 
If you set the game type to "Competitive", you'll get an error message like:
Game alias "Competitive" is unknown, setting default game type=0 mode=1
However, if you change it to "competitive", it works and you'll see the following log entry:
Game alias "competitive" resolved game type=0 mode=1

I only realized that when I tried to switch to the game_alias "Custom", and the Competitive config still loaded. ^^

2024-04-06 06:33 UTC, Lok3rn3t commented
> Hey, the template works flawlessly for me, but it seems like the game_alias cvar is case-sensitive. If you set the game type to "Competitive", you'll get an error message like: Game alias "Competitive" is unknown, setting default game type=0 mode=1 However, if you change it to "competitive", it works and you'll see the following log entry: Game alias "competitive" resolved game type=0 mode=1
> 
> I only realized that when I tried to switch to the game_alias "Custom", and the Competitive config still loaded. ^^

wow, I didn't even know, I think it was working and stopped working after an accidental update, thanks for the comment, I changed the first registers at the type

2024-04-20 17:54 UTC, JamsRepos approved these changes

2024-04-20 18:36 UTC, JamsRepos requested changes
game_mode should be game_alias 

https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers#Game_Modes_.26_Types

2024-04-28 17:45 UTC, JamsRepos approved these changes

2024-05-19 19:37 UTC, JamsRepos approved these changes

2025-09-23 17:56 UTC, closed without merging

2025-10-24 03:09 UTC, Lok3rn3t commented
?