Create cs2.json
PufferPanel/templates pull request #271
Opened 2024-04-21 04:50 UTC by Crazy-Pie

This template will allow you to install a cs2 server

2024-04-21 14:11 UTC, LordRalex requested changes

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +  "data": {
Please refer to other templates for how to order the template.

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +          "chmod +x bin/linuxsteamrt64/cs2"
Should be part of the install

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +      "display": "Game mode ",
Extra space

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +      "value": "192.168.0.1",
Should either be blank or 0.0.0.0

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +      "userEdit": true
IPs also should not be editable by users

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +      "userEdit": true
Ports should not be editable by users

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +          "display": "Vac False"
Use "Enable" or "Disable"

2024-04-21 14:11 UTC, LordRalex commented on CounterStrike2/cs2.json
> +    "workshop_enable": {
Make the naming consistent. This one has _enable on it, but vac doesn't. And both are just "enables". We also don't use _ as much as we can.

2024-04-21 14:12 UTC, LordRalex commented
Folder name also must match the template name, so it has to be "cs2".

2024-05-14 20:55 UTC, Crazy-Pie commented
All comments have been eliminated.

2024-05-14 20:57 UTC, Crazy-Pie reviewed
All comments have been eliminated.

2025-09-23 17:57 UTC, closed without merging